In [1]:
import numpy as np

In [12]:
a = 5.686
#Round Funcation
print(np.round(a))
print(np.round(a,1))
print(np.round(a,2))
print(np.round(a,3))

6.0
5.7
5.69
5.686


In [15]:
a = 5.686
#Ceil Funcation "UP"
print(np.ceil(a))
#floor Funcation "Down"
print(np.floor(a))

6.0
5.0


In [18]:
#Power Funcation " ^ " الاس
print(np.power(5,5))
print(np.power(5,2))

3125
25


In [19]:
#mod Funcation " % " باقي القسمة 
print(np.mod(20,2))
print(np.mod(20,7))

0
6


## Matrix  المصفوفات :

In [21]:
a = [5,6,8,5,2,1,6,8,2,3,6]
b = np.array(a)
print(a)
print(b)
#Note list inculed "," but array not inculed ","

[5, 6, 8, 5, 2, 1, 6, 8, 2, 3, 6]
[5 6 8 5 2 1 6 8 2 3 6]


In [24]:
# Make array empty
a = np.empty((5,5))
print(a)  # كلها اصفار بس مكتوبه بصيغه مختلفه 

[[1.16019755e-310 1.16019746e-310 1.16020032e-310 1.16019755e-310
  1.16020032e-310]
 [1.16019755e-310 1.16020032e-310 1.16019755e-310 1.16019746e-310
  1.16020032e-310]
 [1.16019755e-310 1.16020032e-310 1.16019755e-310 1.16019746e-310
  1.16020032e-310]
 [1.16019755e-310 1.16020032e-310 1.16019755e-310 1.16020032e-310
  1.16019755e-310]
 [1.16019746e-310 1.16020032e-310 1.16019755e-310 1.16020032e-310
  1.16019755e-310]]


In [38]:
a = np.random.uniform(1,10)
print(a)
print("***********************")
s = np.random.uniform(1,10,5)
print(s)
print("***********************")
b = np.random.uniform(1,10 ,25)  # matrix size is  1*25
print(b)
print("***********************")
c = np.resize(b,(5,5))  # matrix size is  5*5
print(c)

5.474564465328279
***********************
[7.99307781 3.13706575 8.72567814 4.40106631 7.32940718]
***********************
[6.67316206 4.59719299 6.63280278 2.44133518 2.71609738 8.74036706
 6.49051818 2.77695052 3.44162138 2.19893187 4.39259988 5.40937497
 6.00163692 6.42923967 2.16188139 6.27318809 1.37685892 9.31039798
 6.83163255 9.96250808 4.25533399 8.07848953 9.59853506 7.81152643
 7.81257844]
***********************
[[6.67316206 4.59719299 6.63280278 2.44133518 2.71609738]
 [8.74036706 6.49051818 2.77695052 3.44162138 2.19893187]
 [4.39259988 5.40937497 6.00163692 6.42923967 2.16188139]
 [6.27318809 1.37685892 9.31039798 6.83163255 9.96250808]
 [4.25533399 8.07848953 9.59853506 7.81152643 7.81257844]]


In [41]:
a = np.random.random((5,5))
a  #numbers are between 0 and 1 

array([[0.15223398, 0.83068056, 0.26339693, 0.32751082, 0.43737827],
       [0.0527545 , 0.75874432, 0.98193897, 0.29238893, 0.9506403 ],
       [0.39880957, 0.5896588 , 0.68893324, 0.30748546, 0.03487579],
       [0.87690132, 0.85903099, 0.97489098, 0.74406557, 0.93614663],
       [0.30237464, 0.08669551, 0.86219642, 0.73653499, 0.42388572]])

In [43]:
b = a  * 10 
b

array([[1.52233985, 8.30680562, 2.6339693 , 3.27510824, 4.37378274],
       [0.52754496, 7.58744322, 9.8193897 , 2.92388929, 9.50640295],
       [3.98809572, 5.89658798, 6.8893324 , 3.07485458, 0.34875786],
       [8.76901319, 8.59030989, 9.74890983, 7.44065566, 9.36146632],
       [3.0237464 , 0.86695513, 8.62196422, 7.36534994, 4.23885722]])

In [54]:
a = np.random.randint(2,10,size = 10)
print(a)
print("*************************************")
b = np.resize(a, (5,2))
print(b)

[4 2 6 4 5 8 7 9 3 7]
*************************************
[[4 2]
 [6 4]
 [5 8]
 [7 9]
 [3 7]]


In [61]:
y = [1,2,3,2,56,2,3,113,0,23,4,3,4]
print(np.random.choice(y))
print(np.random.choice(y))
print(np.random.choice(y))

3
3
1


In [71]:
y = [1,2,3,4,5,6,7,8]
A = np.random.shuffle(y)
print(A)

None


# To Make Zeros Matrix and Ones Matrix

In [75]:
#Zeros Matrix : 
a = np.zeros(8)  # Shape is 1*8
print(a)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [76]:
#Zeros Matrix : 
a = np.zeros((8,8))  # Shape is 8*8
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [77]:
#Ones Matrix : 
a = np.ones(8)  # Shape is 1*8
print(a)

[1. 1. 1. 1. 1. 1. 1. 1.]


In [78]:
#Ones Matrix : 
a = np.ones((8,8))  # Shape is 1*8
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


# I (identity) Matrix مصفوفة الوحدة :

In [80]:
a = np.eye(5)  # Shape 5*5
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [81]:
a = np.eye(9)  # Shape 9*9
a

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

## To Full value in the All values in matrix : Using Full Function

In [88]:
np.full((5,5),35) # Shape 5*5 and the value is 35 

array([[35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35],
       [35, 35, 35, 35, 35]])

In [96]:
np.full((9,9),20) # Shape 9*9 and the value is 20 

array([[20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20],
       [20, 20, 20, 20, 20, 20, 20, 20, 20]])

In [92]:
a = np.arange(18).reshape(6,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [95]:
a = np.arange(27).reshape(3,9) # one Matrix is shape (9*3)
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [94]:
a = np.arange(27).reshape(3,3,3) # Three matrix are shape (3*3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

# Linspace Function:

In [97]:
a = np.linspace(0,20)
a

array([ 0.        ,  0.40816327,  0.81632653,  1.2244898 ,  1.63265306,
        2.04081633,  2.44897959,  2.85714286,  3.26530612,  3.67346939,
        4.08163265,  4.48979592,  4.89795918,  5.30612245,  5.71428571,
        6.12244898,  6.53061224,  6.93877551,  7.34693878,  7.75510204,
        8.16326531,  8.57142857,  8.97959184,  9.3877551 ,  9.79591837,
       10.20408163, 10.6122449 , 11.02040816, 11.42857143, 11.83673469,
       12.24489796, 12.65306122, 13.06122449, 13.46938776, 13.87755102,
       14.28571429, 14.69387755, 15.10204082, 15.51020408, 15.91836735,
       16.32653061, 16.73469388, 17.14285714, 17.55102041, 17.95918367,
       18.36734694, 18.7755102 , 19.18367347, 19.59183673, 20.        ])

In [99]:
a = np.linspace(0,20,5) # Splite by 5 Pieces.
a

array([ 0.,  5., 10., 15., 20.])

In [104]:
a = np.linspace(0,100,20) # Splite by 20 Pieces.
a

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

## Diagnal matrix المصفوفة القطرية :
### تعرفها هي مصفوفة صفريه ما عدا القطر الرئيسي في ارقام مختلفة

In [110]:
a = np.arange(10)
b = np.diag(a)
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 9]])

In [113]:
a = np.arange(10)
b = np.diag(a, k = 3)  # K is increase 3 rows and 3 colmuns 
b

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 2, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 4, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 5, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 6, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 8, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 9],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [117]:
a = np.arange(9).reshape(3,3)
print(a)
b = np.count_nonzero(a)
print(b) # is 8 not zero and 1 element is 0

[[0 1 2]
 [3 4 5]
 [6 7 8]]
8


## To Compare with two martix : Using iscolse Function

In [127]:
a = np.arange(9).reshape(3,3)
b = np.arange(9).reshape(3,3)
c = a * 2 
print(a)
print("")
print(b)
print("")
print(c)

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  2  4]
 [ 6  8 10]
 [12 14 16]]


In [129]:
t = np.isclose(a,b,rtol=0.1)
t

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [130]:
t = np.isclose(a,c,rtol=0.1)
t

array([[ True, False, False],
       [False, False, False],
       [False, False, False]])

In [131]:
a = np.arange(9)
b = np.empty(9)
np.multiply(a,10,out = b)
b

array([ 0., 10., 20., 30., 40., 50., 60., 70., 80.])

In [132]:
a = np.arange(9).reshape(3,3)
b = np.empty(9).reshape(3,3)
np.multiply(a,10,out = b)
b

array([[ 0., 10., 20.],
       [30., 40., 50.],
       [60., 70., 80.]])

## Some Feature of Add and multiply in numpy

In [133]:
a = np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [135]:
b = np.add.reduce(a)  #بيجمع كل القيم في قيمه واحدة بس 
b

105

In [136]:
b = np.add.accumulate(a) # العنصر بيكون مجموع العناصر اللي قبلهم 
b

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105], dtype=int32)

In [139]:
a = np.arange(2,8)
print(a)
b = np.multiply.reduce(a) #بيضرب كل العناصر في بعضها ز يطلع قيمة واحدة بس 
print(b)

[2 3 4 5 6 7]
5040


In [141]:
a = np.arange(2,8)
print(a)
b = np.multiply.accumulate(a) # العنصر بيكون ضرب كل العناصر اللي قبله 
b

[2 3 4 5 6 7]


array([   2,    6,   24,  120,  720, 5040], dtype=int32)

In [143]:
a = np.arange(2,8)
print(a)
b = np.multiply.outer(a,a) #بيضرب الصف الاول في اول عنصر و دا كدا اول صف في المصوفوفة الجديدة 
b

[2 3 4 5 6 7]


array([[ 4,  6,  8, 10, 12, 14],
       [ 6,  9, 12, 15, 18, 21],
       [ 8, 12, 16, 20, 24, 28],
       [10, 15, 20, 25, 30, 35],
       [12, 18, 24, 30, 36, 42],
       [14, 21, 28, 35, 42, 49]])

# Some info about the matrix:
### (len(),size(),shape(),ndim(),dtype())

In [152]:
a = np.arange(15)
b = np.size(a)   #Size of matrix
b

15

In [148]:
a = np.arange(12).reshape(3,4)
b = np.size(a)  #Size of matrix
b

12

In [149]:
a = np.arange(15)
b = np.shape(a) #Shape of matrix
b

(15,)

In [151]:
a = np.arange(12).reshape(3,4)
b = np.shape(a)  #Shape of matrix
b

(3, 4)

In [155]:
a = np.arange(15)
print(a)
b = len(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
15


In [158]:
a = np.arange(15).reshape(3,5)
print(a)
print("**************")
b = len(a)  # Count of the rows 
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
**************
3


In [159]:
a = np.arange(25).reshape(5,5)
print(a)
print("**************")
b = len(a)  # Count of the rows 
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
**************
5


In [161]:
a = np.arange(15).reshape(3,5)
print(a)
print("**************")
b = a.dtype
print(b) #data type of the matrix 

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
**************
int32


In [164]:
a = np.array(["soso","moso","osoo","noso"])
print(a)
print("**************")
b = a.dtype
print(b) #data type of the matrix  U4 Means string

['soso' 'moso' 'osoo' 'noso']
**************
<U4


## How to make matrix with format function:

In [166]:
a = np.matrix("{} {} ; {} {}".format(1,2,3,4))
a

matrix([[1, 2],
        [3, 4]])

In [167]:
a = np.matrix("{} {} ; {} {} ; {} {}".format(1,2,3,4,5,6))
a

matrix([[1, 2],
        [3, 4],
        [5, 6]])

In [168]:
a = np.matrix("{} {} {} ; {} {} {} ; {} {} {}".format(1,2,3,4,5,6,7,8,9))
a

matrix([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [173]:
print(a)
print("***********")
b = np.trace(a)  # لجمع القطر الرئيسي في المصفوفة 
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
***********
15


In [175]:
a = np.matrix("{} {} ; {} {} ; {} {}".format(1,2,3,4,5,6))
print(a)
print("***********")
b = np.trace(a)  # لجمع القطر الرئيسي في المصفوفة 
print(b)

[[1 2]
 [3 4]
 [5 6]]
***********
5


## To Caculate the determinant and eigan Value of the matrix:

In [183]:
a = np.arange(2,11).reshape(3,3)
b = np.linalg.det(a)
b

0.0

In [185]:
a = np.matrix("{} {} {} ; {} {} {} ; {} {} {}".format(1,2,3,4,5,6,7,8,9))
print(a)
b = np.linalg.det(a)  #determinant value
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
6.66133814775094e-16


In [186]:
a = np.matrix("{} {} {} ; {} {} {} ; {} {} {}".format(10,25,30,20,6,12,6,8,9))
print(a)
b = np.linalg.det(a)  #determinant value
print(b)

[[10 25 30]
 [20  6 12]
 [ 6  8  9]]
600.0


In [189]:
a = np.matrix("{} {} {} ; {} {} {} ; {} {} {}".format(1,2,3,4,5,6,7,8,9))
print(a)
print("**********************")  #eigenvalues
b = np.linalg.eig(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
**********************
(array([ 1.61168440e+01, -1.11684397e+00, -4.22209278e-16]), matrix([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))


In [191]:
a = np.matrix("{} {} {} ; {} {} {} ; {} {} {}".format(10,25,30,20,6,12,6,8,9))
print(a)
b = np.linalg.eig(a) #eigenvalues
print(b)

[[10 25 30]
 [20  6 12]
 [ 6  8  9]]
(array([ 39.76424276, -13.65960359,  -1.10463917]), matrix([[-0.77165014, -0.67355792, -0.1368736 ],
        [-0.56256053,  0.73467953, -0.73548663],
        [-0.29678563, -0.08102916,  0.66356992]]))


# splitting of the matrix:

In [195]:
a = np.arange(15)
print(a)
print("")
print(a[3])
print("")
print(a[2:8])
print("")
print(a[0:10:2])
print("")
print(a[-1])
print("")
print(a[-3:-1])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

3

[2 3 4 5 6 7]

[0 2 4 6 8]

14

[12 13]


In [199]:
a = np.arange(100).reshape(10,10)
print(a)
print("")
print(a[3])  # get the 3 row
print("")
print(a[2:8]) # get the 2 row to 7 row
print("")
print(a[0:10:2]) # get the 0 row to 9 row by the step 2
print("")
print(a[-1]) # get the last row
print("")
print(a[-3:-1]) # get the last to -2

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[30 31 32 33 34 35 36 37 38 39]

[[20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]]

[[ 0  1  2  3  4  5  6  7  8  9]
 [20 21 22 23 24 25 26 27 28 29]
 [40 41 42 43 44 45 46 47 48 49]
 [60 61 62 63 64 65 66 67 68 69]
 [80 81 82 83 84 85 86 87 88 89]]

[90 91 92 93 94 95 96 97 98 99]

[[70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]]


In [ ]:
a = np.arange(100).reshape(10,10)


In [200]:
print(a)
print("")
print(a[3,2])  # لو في فصله ما بين الفتره ف دا بيدخل يجيب القيم اللي جوه علي حسب ما مكتوب 
print("")
print(a[2:8,5])
print("")
print(a[0:10:2,3:6])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

32

[25 35 45 55 65 75]

[[ 3  4  5]
 [23 24 25]
 [43 44 45]
 [63 64 65]
 [83 84 85]]


# Split in matrix:

In [214]:
x = np.arange(10)
x1,x2,x3 = np.split(x ,(3,5))
print(x1)
print(x2)
print(x3)

[0 1 2]
[3 4]
[5 6 7 8 9]


In [209]:
x = np.arange(15)
x1,x2,x3 = np.split(x , (2,8))
print(x1)
print(x2)
print(x3)

[0 1]
[2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]


## To acess value in matrix :

In [218]:
a = np.arange(9).reshape(3,3)
print(a)
print(" ")
print(a[2][1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
 
7


In [224]:
a = np.arange(27).reshape(3,3,3)
print(a)
print("")
print(a[0][1][2]) # frist is number of array and second is number of row third is the number of column
print("")
print(a[1][2][2])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
 
5

17


# To concatenate two or more matrix: 
### Using(vstack(), hstack(), concatenate())

In [228]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = np.vstack((a,b))   # بشكل راسي يعني عدد الاعمده لازم يكون متساوي في المصفوفتين
c

array([[10, 16, 16],
       [14, 18, 18],
       [10, 11, 12],
       [18,  5, 12],
       [ 9, 16,  6],
       [13, 14,  6]])

In [231]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 15).reshape(5,3)
c = np.vstack((a,b))   # بشكل راسي يعني عدد الاعمده لازم يكون متساوي في المصفوفتين
c

array([[13, 14,  6],
       [11, 17, 16],
       [ 6,  6, 18],
       [18,  7,  5],
       [18, 12,  6],
       [17, 14, 16],
       [ 8, 15, 15],
       [10,  8, 15]])

In [232]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = np.hstack((a,b))   # بشكل افقي يعني عدد الصفوف لازم يكون متساوي في المصفوفتين
c

array([[19, 19,  5,  5, 15, 10],
       [ 9, 15,  7, 10,  5, 19],
       [ 9, 18,  7,  5, 13, 12]])

In [233]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 15).reshape(3,5)
c = np.hstack((a,b))   # بشكل افقي يعني عدد الصفوف لازم يكون متساوي في المصفوفتين
c

array([[ 9, 16, 14, 12, 13, 11,  6, 11],
       [19, 16,  5,  8, 14,  9,  8,  5],
       [16,  7, 12, 18,  5, 12, 15, 11]])

In [235]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = np.concatenate([a,b] , axis = 0) # لو بتساوي صفر يعني هنضم راسي مع بعض ولازم شرط بتاع الراسي ثابت 
t = np.concatenate([a,b] , axis = 1)   # لو بتساوي واحد يعني هيضم افقي مع بعض و لازم الشرط بتاع الافقي ثابت 
print(c)
print(t)

[[19 17 11]
 [18  9 15]
 [12  7  6]
 [18 16 17]
 [17 10 10]
 [ 7 17 12]]
[[19 17 11 18 16 17]
 [18  9 15 17 10 10]
 [12  7  6  7 17 12]]


In [239]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 15).reshape(5,3)
c = np.concatenate([a,b] , axis = 0) # لو بتساوي صفر يعني هنضم راسي مع بعض ولازم شرط بتاع الراسي ثابت 
print(c)


[[16 18  7]
 [ 9  8 16]
 [13 17  5]
 [16 13 11]
 [10  8  9]
 [10  7 19]
 [17 18 10]
 [11 13 10]]


In [240]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 15).reshape(3,5)
t = np.concatenate([a,b] , axis = 1)   # لو بتساوي واحد يعني هيضم افقي مع بعض و لازم الشرط بتاع الافقي ثابت 
print(t)

[[13 19  6  6 11 18 16  8]
 [ 7  9 13 17 15  6 16 11]
 [12  6 10 13 18 10 17 11]]


## Some important funcations in numpy:

In [249]:
a = np.random.randint(2,20,size = 25).reshape(5,5)
print(a)
print("")
b = np.max(a)
print(b)

[[ 9 15 14 14  8]
 [ 8  3  3  3  8]
 [ 7  5  6  4 13]
 [17 19 10 16  3]
 [ 3  2  4  3 10]]

19


In [250]:
a = np.random.randint(2,20,size = 25).reshape(5,5)
print(a)
print("")
b = np.min(a)
print(b)

[[19 13 19  4 10]
 [ 2  7  4 11 19]
 [19 10 17 14  2]
 [14  3 15 19 12]
 [16 10 10 12 14]]

2


In [251]:
a = np.random.randint(2,20,size = 25).reshape(5,5)
print(a)
print("")
b = np.argmax(a)  # بيطبع الترتيب اكبر مكان 
print(b)

[[ 8  5 18 19 12]
 [15 12 15  5 16]
 [15 13 16 13 16]
 [ 8 15 14 18 13]
 [ 4 18 14  2  2]]

3


In [252]:
a = np.random.randint(2,20,size = 25).reshape(5,5)
print(a)
print("")
b = np.argmin(a) #بيطبع مكان اصغر مكان 
print(b)

[[ 7  3 14 12  7]
 [14  6  2  9  3]
 [11  6 14 13 10]
 [ 7 13 14 12 10]
 [17  4 16  8 18]]

7


## To calculate Variance , Covaricane :

In [256]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
print(a)
print("")
b = np.var(a)
print(b)

[[13  7 11]
 [ 9 11 19]
 [ 5 19  8]]

21.77777777777778


In [257]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
print(a)
print("")
b = np.cov(a)
print(b)

[[14 10  6]
 [ 5 11 11]
 [12 15 17]]

[[ 16.         -12.         -10.        ]
 [-12.          12.           8.        ]
 [-10.           8.           6.33333333]]


## Some operations in matrix : (+,-,/,*)

In [258]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = a + b
print(a)
print("")
print(b)
print("")
print(c)

[[10 13 13]
 [ 5 13 14]
 [19  5 16]]

[[17 14 19]
 [14 17 11]
 [13  8  5]]

[[27 27 32]
 [19 30 25]
 [32 13 21]]


In [259]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = a - b
print(a)
print("")
print(b)
print("")
print(c)

[[ 6 11 15]
 [14 16  7]
 [ 5 10  6]]

[[14  6  9]
 [16 17  6]
 [12  5 12]]

[[-8  5  6]
 [-2 -1  1]
 [-7  5 -6]]


In [260]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = a / b  # هنا بيقسم كل رقم علي اللي قدامه و بس لان مفيش قسمة في المصفوفات
print(a)
print("")
print(b)
print("")
print(c)

[[16  8 11]
 [ 8  6 15]
 [11 15 19]]

[[ 8 15 18]
 [16 13  9]
 [16  5  9]]

[[2.         0.53333333 0.61111111]
 [0.5        0.46153846 1.66666667]
 [0.6875     3.         2.11111111]]


In [261]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = a * 2
print(a)
print("")
print(c)

[[15 10  9]
 [14 13  5]
 [ 7 18 11]]

[[30 20 18]
 [28 26 10]
 [14 36 22]]


In [262]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = a / 2  # هنا بيقسم كل رقم علي اللي قدامه و بس لان مفيش قسمة في المصفوفات
print(a)
print("")
print(c)

[[ 6 18 15]
 [15  9  8]
 [13 12 16]]

[[3.  9.  7.5]
 [7.5 4.5 4. ]
 [6.5 6.  8. ]]


In [264]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = a + 2  
print(a)
print("")
print(c)

[[ 6  7  6]
 [14  8  6]
 [ 8 10  9]]

[[ 8  9  8]
 [16 10  8]
 [10 12 11]]


In [265]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = a - 2  
print(a)
print("")
print(c)

[[14 11 17]
 [ 9 19 10]
 [14  8  6]]

[[12  9 15]
 [ 7 17  8]
 [12  6  4]]


In [266]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = a ** 2  # power 2
print(a)
print("")
print(c)

[[17 19 11]
 [10 14 16]
 [13 16 12]]

[[289 361 121]
 [100 196 256]
 [169 256 144]]


In [267]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = np.dot(a,b)  
print(a)
print("")
print(b)
print("")
print(c)

[[18 16 19]
 [11 19 16]
 [ 8 13 10]]

[[18  9  8]
 [ 7  6  6]
 [18 13 18]]

[[778 505 582]
 [619 421 490]
 [415 280 322]]


In [268]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = a * b # هنا ضرب عادي كل عنص في اللي قدامه مش ضرب المصفوفات بتاع القوانين 
print(a)
print("")
print(b)
print("")
print(c)

[[14  7  5]
 [14 13  5]
 [17  6  7]]

[[11 13 17]
 [10  5 12]
 [10 14  9]]

[[154  91  85]
 [140  65  60]
 [170  84  63]]


In [269]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 15).reshape(3,5) # لازم عدد عواميد المصفوفة الاولي بيساوي عدد صفوف المصفوفة التانية مهممممممم
c = np.dot(a,b)  
print(a)
print("")
print(b)
print("")
print(c)

[[ 7  8  9]
 [10 18 14]
 [ 9 11 12]]

[[19 12 12 18 10]
 [17  8 18  6 16]
 [ 7 15  5 16 19]]

[[332 283 273 318 369]
 [594 474 514 512 654]
 [442 376 366 420 494]]


In [270]:
a = np.random.randint(5,20,size = 12).reshape(4,3)
b = np.random.randint(5,20,size = 15).reshape(3,5) # لازم عدد عواميد المصفوفة الاولي بيساوي عدد صفوف المصفوفة التانية مهممممممم
c = np.dot(a,b)  
print(a)
print("")
print(b)
print("")
print(c)

[[12 18  9]
 [16 11  7]
 [17 12 11]
 [19 15 16]]

[[16 16  6  6 19]
 [ 9  5  6 17  9]
 [ 7 12  5  6  8]]

[[417 390 225 432 462]
 [404 395 197 325 459]
 [457 464 229 372 519]
 [551 571 284 465 624]]


##  Some basic Function in matrix: (log,sin,cos,tan,inverse,dot,sort,mean,std,var)

In [271]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.log(a)
b

array([[1.60943791, 2.30258509, 1.60943791],
       [2.30258509, 1.60943791, 1.79175947],
       [2.7080502 , 1.79175947, 1.79175947]])

In [272]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.sin(a)
b

array([[ 0.6569866 ,  0.6569866 , -0.54402111],
       [ 0.14987721, -0.54402111, -0.28790332],
       [ 0.14987721,  0.6569866 ,  0.42016704]])

In [273]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.cos(a)
b

array([[ 0.66031671, -0.27516334, -0.27516334],
       [ 0.0044257 , -0.14550003, -0.27516334],
       [ 0.66031671,  0.84385396,  0.0044257 ]])

In [274]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.tan(a)
b

array([[   7.24460662, -225.95084645,   -0.8559934 ],
       [  -0.8559934 , -225.95084645,    0.87144798],
       [   3.49391565,   -0.8559934 ,    7.24460662]])

In [275]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.linalg.inv(a)
b

array([[ 0.36175115,  0.01382488, -0.25576037],
       [-0.23732719,  0.07373272,  0.1359447 ],
       [ 0.10599078, -0.11059908,  0.04608295]])

In [277]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = a.mean()
b

11.11111111111111

In [278]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = a.std()
b

3.496029493900505

In [279]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = a.var()
b

14.666666666666666

In [280]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = a**2
b

array([[361, 324, 324],
       [ 81, 324, 196],
       [ 64,  49,  25]], dtype=int32)

In [281]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
b = np.random.randint(5,20,size = 9).reshape(3,3)
c = np.dot(a,b)
c

array([[304, 325, 585],
       [250, 263, 491],
       [306, 312, 599]])

In [284]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
print(a)
print("")
b = np.sort(a,axis=0)  #راسي 
print(b)

[[13  9  6]
 [13 15  7]
 [ 9 10  7]]

[[ 9  9  6]
 [13 10  7]
 [13 15  7]]


In [285]:
a = np.random.randint(5,20,size = 9).reshape(3,3)
print(a)
print("")
b = np.sort(a,axis=1)  #افقي 
print(b)

[[ 7  5  8]
 [13 18  7]
 [14 10 13]]

[[ 5  7  8]
 [ 7 13 18]
 [10 13 14]]


# How to read from file with Numpy:

In [293]:
path = "D:\\Learn\\Hesham Asem\\Python-C\\Numpy\\Data.txt"
dtype1 = np.dtype([("geneder","|S1"),("height","f8")])
Data = np.loadtxt(path , dtype = dtype1 , skiprows = 9 , usecols = (1,3))
print(Data)

[(b'M', 1.82) (b'M', 1.77) (b'F', 1.68) (b'M', 1.72) (b'F', 1.78)
 (b'F', 1.6 ) (b'M', 1.72) (b'M', 1.83) (b'F', 1.56) (b'F', 1.64)
 (b'M', 1.63) (b'M', 1.67) (b'M', 1.66) (b'F', 1.59) (b'F', 1.7 )
 (b'M', 1.97) (b'F', 1.66) (b'F', 1.63) (b'M', 1.69)]


In [295]:
path = "D:\\Learn\\Hesham Asem\\Python-C\\Numpy\\Data2.txt"
data = np.genfromtxt(path, skip_header=1,
                  dtype=[('student','u8'),
                         ('gender','S1'),('black','f8'),
                         ('colour','f8')],delimiter=',',
                         missing_values='X')

print(data)


[(1, b'F', 18.72, 31.11) (2, b'F', 21.14, 52.47) (3, b'F', 19.38, 33.9 )]


# Polynomials : to get best fit line with many point


In [316]:
X = np.array([0,20,40,60,80,100,120,140,160,180])
Y = np.array([10,9,8,7,6,5,4,3,2,1])
print(X)
print("")
print(Y)
print("")
poly = np.polynomial.Polynomial
points , stats = poly.fit(X,Y,1,full = True)
print(points)

[  0  20  40  60  80 100 120 140 160 180]

[10  9  8  7  6  5  4  3  2  1]

5.500000000000001 - 4.500000000000003 x**1


In [318]:
X = np.random.randint(2,20,size=20)
Y = np.random.randint(2,20,size=20)
print(X)
print("")
print(Y)
print("")
ploy = np.polynomial.Polynomial
points , stats = poly.fit(X,Y,2,full=True)
print(points)

[ 9  5  6  5 17 15 18  9  8  6 12 18 10  7 18 15 14 14  6 15]

[ 5  5  3  7  8 10 14 10 13 18  5  2 18 12  9 18 11  8  2 18]

12.10063401671164 + 1.185268239967396 x**1 - 4.477676022009249 x**2


In [319]:
X = np.array([0,20,40,60,80,100,120,140,160,180])
Y = np.array([10,9,8,7,6,5,4,3,2,1])
print(X)
print("")
print(Y)
print("")
ploy = np.polynomial.Polynomial
points , stats = poly.fit(X,Y,2,full=True)
print(points)

[  0  20  40  60  80 100 120 140 160 180]

[10  9  8  7  6  5  4  3  2  1]

5.499999999999999 - 4.500000000000003 x**1 + 0.0 x**2


## Poly1d Function using to create equation with any degree:

In [321]:
a = np.poly1d((1))
b = np.poly1d((1,5))
c = np.poly1d((2,-7,14))
print(a)
print("******************")
print(b)
print("******************")
print(c)

 
1
******************
 
1 x + 5
******************
   2
2 x - 7 x + 14


In [327]:
a = np.poly1d((1)) 
b = np.poly1d((1,5)) 
c = np.poly1d((2,-7,14))
s = a(2) # X = 2 in a equation   بيعوض في المعادلات الام اللي فوق
d = b(6) # X = 6 in a equation
f = c(7) # X = 7 in a equation
print(s)
print("******************")
print(d)
print("******************")
print(f)

1
******************
11
******************
63


## Ployval Function بتعوض في المعادلات بالقيم اللي بتختارها و بتكريت جواها المعادلات عادي 

In [331]:
e = np.poly1d((1,-7,12))
print(e)
print("*****************")
a = np.polyval(e,2) # X = 2 
print(a)

   2
1 x - 7 x + 12
*****************
2


In [332]:
e = np.poly1d((1,-7,12,5))
print(e)
print("*****************")
a = np.polyval(e,5) # X = 5 
print(a)

   3     2
1 x - 7 x + 12 x + 5
*****************
15


In [333]:
e = np.poly1d((1,-7,12))
print(e)
print("*****************")
a = np.polyval(e,4) # X = 4 
print(a)

   2
1 x - 7 x + 12
*****************
0


## Polyder Function لعمل المشتقه من اي درجة علي حسب اختيارك و بيتعمل المعادلة جواها :

In [337]:
e = np.poly1d((1,-7,14))
print(e)
print("*************************")
a = np.polyder(e,1)   # المشتقة الاولي من المعادلة
print(a)
print("*************************")
f = np.polyder(e,2)  # المشتقة التانية من المعادلة
print(f)

   2
1 x - 7 x + 14
*************************
 
2 x - 7
*************************
 
2


In [338]:
e = np.poly1d((1,-7,14,6,8,2))
print(e)
print("*************************")
a = np.polyder(e,1)   # المشتقة الاولي من المعادلة
print(a)
print("*************************")
f = np.polyder(e,2)  # المشتقة التانية من المعادلة
print(f)
print("*************************")
t = np.polyder(e,4)  # المشتقة الرابعه من المعادلة
print(t)

   5     4      3     2
1 x - 7 x + 14 x + 6 x + 8 x + 2
*************************
   4      3      2
5 x - 28 x + 42 x + 12 x + 8
*************************
    3      2
20 x - 84 x + 84 x + 12
*************************
 
120 x - 168


## Roots Funcion لايجاد جزور المعادلة 
## جزور المعادلة هي الارقام التي تجعل قيمة المعادلة كلها تساوي الصفر 

In [342]:
e = np.poly1d((1,-7,12))
print(e)
print("****************************")
a = np.roots(e)
print(a)   # لان المعادلة من الدرجة التانية و فيها اكس تربيع لذلك ليها اتنين جزور تخلي المعادلة تساوي الصفر عند التعويض

   2
1 x - 7 x + 12
****************************
[4. 3.]


In [346]:
e = np.poly1d((1,5,-6))
print(e)
print("****************************")
a = np.roots(e)
print(a)   # لان المعادلة من الدرجة التانية و فيها اكس تربيع لذلك ليها اتنين جزور تخلي المعادلة تساوي الصفر عند التعويض

   2
1 x + 5 x - 6
****************************
[-6.  1.]


## poltfit Function :

In [354]:
X = np.random.randint(2,20,size = 5)
Y = np.random.randint(2,20,size = 5)
print(X)
print("******************************")
print(Y)
print("******************************")
z = np.polyfit(X,Y,2)  # U من الدرجة التانيه علي شكل 
print(z)

[ 3  8 17  4  2]
******************************
[ 4 14 10 17  2]
******************************
[-0.19500902  4.09200535 -3.52694697]
